services:

  mongodb:
    image: mongo:7
    container_name: socialnet-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db


  qdrant:
    image: qdrant/qdrant:latest
    container_name: socialnet-qdrant
    restart: unless-stopped

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_storage:/qdrant/storage


  ollama:
    image: ollama/ollama
    container_name: socialnet-ollama
    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama


  server:
    build:
      context: ./server

    command: npm run server

    container_name: socialnet-server
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - ./server/.env

    environment:
      NODE_ENV: development
      PORT: 8000

    volumes:
      - ./uploads:/app/uploads

    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/
            - "*.log"

        - action: rebuild
          path: ./server/package.json

    depends_on:
      - mongodb
      - ollama
      - qdrant
      - socket


  socket:
    build:
      context: ./socket

    command: npm run dev

    container_name: socialnet-socket
    restart: unless-stopped

    ports:
      - "7000:7000"

    env_file:
      - ./socket/.env

    environment:
      NODE_ENV: development
      PORT: 7000
      FRONTEND_URL: http://localhost:3000

    develop:
      watch:
        - action: sync
          path: ./socket
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/

        - action: rebuild
          path: ./socket/package.json

    depends_on:
      - mongodb
      - qdrant


  client:
    build:
      context: ./client

    command: npm run dev -- --host 0.0.0.0

    container_name: socialnet-client
    restart: unless-stopped

    ports:
      - "3000:3000"

    env_file:
      - ./client/.env

    environment:
      VITE_API_URL: http://localhost:8000
      VITE_SOCKET_URL: http://localhost:7000

    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/

        - action: rebuild
          path: ./client/package.json

    depends_on:
      - server
      - socket


volumes:
  mongodb_data:
  ollama_data:
  qdrant_storage: